#!/usr/bin/env python
from ast import arguments
import subprocess
import optparse

#ფუნქციაში მოქცევა
def changeMac(interface, newMac):
    #ცვლადების გამოტანა ეკრანზე
    print ("[+] Changing MAC address of " + interface + " to " + newMac)

    #ლოგიკა
    subprocess.call(["ifconfig", interface, "down"])
    subprocess.call(["ifconfig", interface, "hw", "ether", newMac])
    subprocess.call(["ifconfig", interface, "up"])
    subprocess.call(["ifconfig", interface])

# გარედან მიწოდებული არგუმენტების აღქმა
parser = optparse.OptionParser()
parser.add_option("-i", "--interface", dest="int", help="Name Of Interface, What MAC You Want To Change")
parser.add_option("-m", "--macaddress", dest="nmac", help="Here Goes New MAC address. MAC address should be begin on even eg 12 or 24")
(options, arguments) = parser.parse_args()

# ცვლადებისთვის არგუმენტების მინიჭება აღარ გვჭირდება ფუნქციაში გავწერეთ და იმიტომ
# interface = options.interface
# newMac = options.new_mac


changeMac(options.int, options.nmac)



