#!/usr/bin/env python
import subprocess
import optparse


def get_arguments():
    parser = optparse.OptionParser()
    parser.add_option("-i", "--interface", dest="int", help="Name Of Interface, What MAC You Want To Change")
    parser.add_option("-m", "--macaddress", dest="nmac", help="Here Goes New MAC address. MAC address should be begin "
                                                              "on even eg 12 or 24")
    (options, arguments) = parser.parse_args()
    if not options.int:
        parser.error("[-] Please Enter An Interface | Use --help for more information")
    elif not options.nmac:
        parser.error("[-] Please Enter MAC Address | Use --help for more information")
    return options


def changeMac(interface, newMac):
    print("[+] Changing MAC address of " + interface + " to " + newMac)
    subprocess.call(["ifconfig", interface, "down"])
    subprocess.call(["ifconfig", interface, "hw", "ether", newMac])
    subprocess.call(["ifconfig", interface, "up"])
    subprocess.call(["ifconfig", interface])


option = get_arguments()
changeMac(option.int, option.nmac)
